### ISSUE TITLE
bug: error running tests from a lower working directory

### ISSUE THREAD

**Issue by jstensland** [fredrikaverpil/neotest-golang#103]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

The adapter is limiting its search for the `go.mod` file to the current working directory and this is causing test commands to fail.

### Steps To Reproduce

1. Create a go project with a valid `go.mod` file at its root, but with packages in subdirectories.
2. Change directory into one of the packages
3. Run the tests, for example `lua require("neotest").run.run( vim.fn.expand("%:h"))`. This produces a notification with the error
    >  Error  10:46:51 notify.error The selected folder must contain a go.mod file or be a subdirectory of a Go package.

### Expected Behavior

Tests for the package should run

**Comment by jstensland** [comment]
It looks like the adapter is limiting its search to the [the cwd](https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/path.lua#L11).

Perhaps it could search up to find `go.mod`, `go.work` or `.git` to establish the root

**Comment by fredrikaverpil** [comment]
Aha, I think I got it. 

The upwards search stops at the `cwd` today. 

https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/path.lua#L13

I'm not sure if it's a great idea to search further than that.

**Comment by fredrikaverpil** [comment]
I'm not 100% sure about this fix yet, but please go ahead and try it out and see if it solves the problem on your end: https://github.com/fredrikaverpil/neotest-golang/pull/104

**Comment by jstensland** [comment]
I usually do too, so not a blocker for me, but not always.

Neotest's helper stops at HOME if I am reading [this](https://github.com/nvim-neotest/neotest/blob/26ed90509c377d10dbdebd25b7094a886323b32b/lua/neotest/lib/file/init.lua#L357) right. It looks like lspconfig [just keeps searching](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/util.lua#L275) though, so either is probably reasonable.

Matching neotest makes sense to me.

**Comment by jstensland** [comment]
Using the changes in https://github.com/fredrikaverpil/neotest-golang/pull/104, this symptom goes away. Only tested using `go.mod` fwiw

**Comment by fredrikaverpil** [comment]
Aha, nice that you looked into those details. Manny thanks. Let's go for this then. 👍
