### ISSUE TITLE
feature: support table tests for test case structs with no fields

### ISSUE THREAD

**Issue by jstensland** [fredrikaverpil/neotest-golang#155]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Is your feature request related to a problem? Please describe.

I have multiple packages with test cases where there's an anonymous struct of test cases and the cases *do not include fields*. The current support for table tests do not detect these. e.g.

```go
func TestTableTestInlineStructLoopNotKeyed(t *testing.T) {
	for _, tc := range []struct {
		name     string
		x        int
		y        int
		expected int
	}{
		{"TableTest1", 1, 2, 3}, // no `name:` to match on
		{"TableTest2", 3, 4, 7},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if Add(tc.x, tc.y) != tc.expected {
				t.Fail()
			}
		})
	}
}
```

Given the support for this functionality when the field is there, it would be nice to support this form as well.

### Describe the solution you'd like to see.

I would like to be able to run the nearest test case when my cursor is on it, or to run a single test case from the summary

### Describe alternatives you've considered.

The obvious alternative is to just run the full test, which does work.

### Additional context

I tried updated the treesitter query for these. I could only get as far as matchings the struct def with the first argument to run in this form (similar to what exists) but wasn't sure if it's possible to ask treesitter for the index of the sibling in the list of declared field, such that I could identify that name field to capture the test name. It may be good enough to assume its first, given this is just matching a specific code pattern anyways

**Comment by fredrikaverpil** [comment]
We should be able to support this by extending the current treesitter queries: https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/query.lua

If you want to take a stab at it, there are Go tests in `positions_test.go` (in which you would add the test you provided above) as well as a lua test file that asserts that the tests are detected by the neotest-golang adapter in `positions_spec.lua`. There are instructions in the README on how to play around with the treesitter queries in `query.lua` as well as how to run the lua tests with the Makefile.

**Comment by fredrikaverpil** [comment]
Sorry, I somehow missed you already looked into this. 😅 

> I could only get as far as matchings the struct def with the first argument to run in this form (similar to what exists) but wasn't sure if it's possible to ask treesitter for the index of the sibling in the list of declared field, such that I could identify that name field to capture the test name.

I see what you mean. Not sure myself without digging.

**Comment by jstensland** [comment]
Seems possible to just match the first string defined in the struct which is _likely_ the right one. Seems like an option if there's not a better way to index the fields between struct definition and literal definitions

**Comment by fredrikaverpil** [comment]
Please give https://github.com/fredrikaverpil/neotest-golang/pull/156 a try?

**Comment by jstensland** [comment]
Sorry for the long delay. Two things

1. To match other test case detection, how about able also supporting the variation where the struct is defined outside of the for loop? Those are not currently detected. Adjusting my original example, that's something like
```go
func TestTableTestInlineStructLoopNotKeyed(t *testing.T) {
	 testcases := []struct {
		name     string
		x        int
		y        int
		expected int
	}{
		{"TableTest1", 1, 2, 3}, // no `name:` to match on
		{"TableTest2", 3, 4, 7},
	} 
	for _, tc := testcases {
		t.Run(tc.name, func(t *testing.T) {
			if Add(tc.x, tc.y) != tc.expected {
				t.Fail()
			}
		})
	}
}
```


2. I am getting the following error running one of the tests cases
    ```
    Test(s) not associated (not found/executed):  { '/path/to/file_test.go::TestName::"casename"::"secondstringfield"' }
    ```

**Comment by fredrikaverpil** [comment]
Sorry for the silence here. I'm quite busy at work and with life at the moment. I'll have a look when I have the time. Feel free to take a stab at it in case you wish.

**Comment by fredrikaverpil** [comment]
@jstensland I updated the query in #156 
Please give this a try and let me know how this works for you:

```lua
{
  "fredrikaverpil/neotest-golang",
  branch = "table-test-without-struct-fields",
}
```

**Comment by kvalv** [comment]
Hi @fredrikaverpil I stumbled upon the same issue by coincidence and checked out #156. It seems to work quite well on my end, too! :smile:

**Comment by fredrikaverpil** [comment]
Hi @kvalv !

I understand what you mean, but this is actually expected/intended behavior. Neotest gives the adapter the ability to provide treesitter queries so to detect what is considered a test or test case (in the test table). You can see the `t.Run(...)` as a "test body" and is in itself not considered a test on its own. You can see where the green checkmark symbols to appear to understand which one is nearest to where your cursor is at.

I also think (I'm not entirely sure as I'm on the go right now) that Neotest looks upwards the file when it tries to find the nearest test, so to make things more intuitive.

But on a slightly different note, this PR has been open for a long time. Since you have verified that it works for you, I'm thinking we can merge this in. WDYT?

**Comment by kvalv** [comment]
Thanks for the clarification! Makes sense that neotest looks upward when finding the nearest test, so this is intended behaviour :+1: 

> Since you have verified that it works for you, I'm thinking we can merge this in. WDYT?

Sounds great! From what I can see, the PR should resolve this issue :smile:
