### ISSUE TITLE
feature: support tags for go list command

### ISSUE THREAD

**Issue by augbed** [fredrikaverpil/neotest-golang#170]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Is your feature request related to a problem? Please describe.

Currently it's not possible to run tests that have build tags, I can provide -tags as parameter to go_test_args, but when plugin runs go list they are missing and the command fails.

### Describe the solution you'd like to see.

Pass the same tags argument from go_test_args to go list command.

### Describe alternatives you've considered.

Have config argument for plugin itself where arguments to go list could be provided.

**Comment by fredrikaverpil** [comment]
Hi and thanks for the report!

Ok so this is definitively something we should fix. Before I saw #171, I figured we could add a specific `go_list_args` option. I think this would allow more control. What do you think?

**Comment by augbed** [comment]
Hey, no problem. Thank you for your work!

go_list_args sounds good. It might be confusing for a user to know that he needs to pass -tags to both but a note in readme about it is probably good enough. I will update the pull request!

**Comment by fredrikaverpil** [comment]
This was fixed by #172, closing this.
