### ISSUE TITLE
bug: TestMain interpreted as a test

### ISSUE THREAD

**Issue by oleynikandrey** [fredrikaverpil/neotest-golang#182]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

MacOS 14.6.1

### Output from `:checkhealth neotest-golang`

```text
neotest-golang: require("neotest-golang.health").check()

Requirements ~
- OK Binary 'go' found on PATH: /opt/homebrew/bin/go
- OK Found go.mod file for ...
- OK Treesitter parser for go is installed
- OK neotest is available
- OK nvim-treesitter is available
- OK nio is available
- OK plenary is available

DAP (optional) ~
- OK Binary 'dlv' found on PATH: /Users/user/.local/share/nvim/mason/bin/dlv
- OK dap is available
- OK dapui is available
- OK dap-go is available
```

### Describe the bug

If a test file has `TestMain` for test setup and teardown, the plugin interprets this function as a test and tries to run it, but it fails with the following warning:
```
Test(s) not associated (not found/executed):  { "..._test.go::TestMain" }
```

### Steps To Reproduce

Run all tests

```go
package test

import (
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	code := m.Run()
	os.Exit(code)
}

func TestDummy(t *testing.T) {
}
```

### Expected Behavior

TestDummy executed without warnings.

### Your Lua setup

```Lua
return {
  {
    "nvim-neotest/neotest",
    config = function()
      require("neotest").setup({
        adapters = {
          require("neotest-golang")({
            go_test_args = { "-count=1", "-tags=integration" },
            go_list_args = { "-tags=integration" },
            dap_go_opts = {
              delve = {
                build_flags = { "-tags=integration" },
              },
            },
          }),
        },
      })
    end,
  },
}
```

**Comment by fredrikaverpil** [comment]
Hey @oleynikandrey and thanks for the report!

Indeed, this should not be causing that warning and would ideally not even show up as a test in neotest. I have a PR up to fix this in #183
