### ISSUE TITLE
feature: ginkgo support

### ISSUE THREAD

**Issue by hown3d** [fredrikaverpil/neotest-golang#204]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Is your feature request related to a problem? Please describe.

Ginkgo does have it's own structure on how test cases are build: https://onsi.github.io/ginkgo/#writing-specs

Some places where ginkgo is used:
- [ Kubernetes E2E Framework](https://github.com/kubernetes/kubernetes/blob/4dc7a48ac6fb631a84e1974772bf7b8fd0bb9c59/test/e2e/framework/README.md)
- [Gardener](https://github.com/gardener/gardener)

## Requirements to support ginkgo

- [ ] tree-sitter query
- [ ] test command
- [ ] Parse output from ginkgo

### Describe the solution you'd like to see.

Add a tree-sitter query to capture tests written with Ginkgo

### Describe alternatives you've considered.

Ginkgo has the possibility to print it's outline with [`ginkgo outline --format=json $PACKAGE`](https://onsi.github.io/ginkgo/#creating-an-outline-of-specs) in their own data structure.
For example the 
Parsing this into neotest.positions would be possible, but using native treesitter seems to be the easier option.

### Additional context

![Bildschirmfoto 2024-10-14 um 01 29 22](https://github.com/user-attachments/assets/11ff4402-ffc9-4ed9-b247-8593d7089d78)

I would be happy to implement support since we use ginkgo a lot in our code base 😃

**Comment by fredrikaverpil** [comment]
Hey @hown3d,

I haven't used ginkgo and I don't plan on adding this support myself but I'm absolutely open for PRs here and I'll be happy to provide guideance.

I'm curious what steps you took to get the tests to be detected in your screenshot, and if you only got the test summary to show the tests - but not being able to run them, for example.

Have you looked at how the optional testify feature was implemented?
I feel we might want to do something similar here, which you would opt-in to.

After having quickly skimmed the ginkgo link you provided over morning coffee, it looks like the test output will be `go test` output, which means you can piggy back on the current test output processing, which is neat. But what about the test invocation itself, would you want to use another command than `go test` to invoke test(s)?

I'm looking into potentially supporting custom test runners in #189 which perhaps could be  interesting here, in case it would help to use `ginkgo` to execute tests. You can see how I've configured `gotestsum`, which piggybacks on the runspecs and test output processing implemented for `go test`, but implements its own test invocation command: https://github.com/fredrikaverpil/neotest-golang/pull/189/files#diff-59de0e930211d324b35ad4beccf973061d9ab55415ebfaec0d9ee3c265f96746R63

**Comment by hown3d** [comment]
Happy to participate!

I've been playing around to get support for Ginkgo tests. The tests from the screenshot are done using this Tree-sitter query:
```
[[
    ; query for ginkgo tests
    (call_expression
      function: (identifier) @ginkgo_spec  (#match? @ginkgo_spec "^(Describe|Context|It)$")
        arguments: (argument_list
          (interpreted_string_literal) @test.name
      ) @test.definition
    )
]]
```

# Test execution
I was thinking about using the focus flag from ginkgo which focuses on a dedicated [Spec](https://onsi.github.io/ginkgo/#writing-specs) with regex. This is only suitable though when actually targeting a ginkgo Spec. 

Using the tests from the screenshot as an example: \
Running the test **Books -> Categorizing Books -> with more than 300 pages -> should be a novel** could be achieved by using 
`ginkgo run --focus "Books Categorizing Books with more than 300 pages should be a novel"`. This focus "regex" does differ though from the go test regex. So if using ginkgo as the runner, we would need to distinguish between standard go tests and Ginkgo specs, which is not possible (correct me if I'm wrong) not possible from the same adapter. 

# Test parsing

Unfortunately Ginkgo does not use the default test output from go json instead it uses it's [own data structure for reports](https://github.com/onsi/ginkgo/blob/104752fa2e97f04b1300754e710c419a63d2d30c/types/types.go#L15).

# Conclusion

My idea was to create a second adapter that is only used to parse Ginkgo specs. There we can adapt to different regex invocation and result parsing.

**Comment by fredrikaverpil** [comment]
Given if I merge in something like #189 you could actually implement all this here in this adapter. But it sounds like you won't benefit much from doing that in case _everything_ differs (treesitter query, execution command, test output parsing). Then maybe it's better you take ownership of this and build a separate adapter, as you wouldn't be "trapped" in my repo and in the way I structure the code etc.

**Comment by fredrikaverpil** [comment]
I'm going to close this. If you still think neotest-golang should provide ginkgo support and if you're willing to contribute, we can re-open this 😄
