### ISSUE TITLE
bug: updating nvim-treesitter to 0.9.2 doesn't detect tests

### ISSUE THREAD

**Issue by minizilla** [fredrikaverpil/neotest-golang#207]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

NixOS 24.11 (Vicuna)

### Output from `:checkhealth neotest-golang`

```text
neotest-golang: require("neotest-golang.health").check()

Requirements ~
- OK Binary 'go' found on PATH: /nix/store/ipdsqmj2pa49qam4j3hml54ambcz3acy-go-1.19.8/bin/go
- OK Found go.mod file for /home/minizilla/personal/testr/example_test.go in /home/minizilla/personal/testr/go.mod
- OK Treesitter parser for go is installed
- OK neotest is available
- OK nvim-treesitter is available
- OK nio is available
- OK plenary is available

DAP (optional) ~
- OK Binary 'dlv' found on PATH: /run/current-system/sw/bin/dlv
- OK dap is available
- WARNING dapui is not available
- OK dap-go is available
```

### Describe the bug

Updating `nvim-treesitter` to 0.9.2 doesn't detect tests, resulting in `No tests found`.
Many neotest adapter also report the same thing, one of them is [neotest-jest#99](https://github.com/nvim-neotest/neotest-jest/issues/99), their fixed it in this [PR](https://github.com/nvim-neotest/neotest-jest/pull/100).

Although this is breaking change, I think its necessary since `nvim-treesitter` is a big part of neotest.

Downgrading back to 0.9.1 does works too.

### Steps To Reproduce

1. Use nvim-treesitter 0.9.2
2. Run test (resulting in `No test found`)

### Expected Behavior

The test should works.

**Comment by fredrikaverpil** [comment]
Hey @minizilla please do not use nvim-treesitter tags. They are too old. Version 0.9.2 is from January 19th, around 9 months old. The last commit to the main branch was today. Just go with the latest commit on their main branch and you'll be fine.

**Comment by fredrikaverpil** [comment]
I'm closing this issue. Let me know if you think we should reopen it.
