### ISSUE TITLE
bug: test passed but got no tests associated

### ISSUE THREAD

**Issue by PabloRai** [fredrikaverpil/neotest-golang#210]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Windows 11

### Output from `:checkhealth neotest-golang`

```text
==============================================================================
neotest-golang: require("neotest-golang.health").check()

Requirements ~
- OK Binary 'go' found on PATH: C:\Program Files\Go\bin\go.EXE
- OK Found go.mod file for C:\Users\Pablo\go\src\github\testproj\main\something_test.go in C:\Users\Pablo\go\src\github\testproj\go.mod
- OK Treesitter parser for go is installed
- OK neotest is available
- OK nvim-treesitter is available
- OK nio is available
- OK plenary is available

DAP (optional) ~
- OK Binary 'dlv' found on PATH: C:\Users\Pablo\go\bin\dlv.EXE
- OK dap is available
- OK dapui is available
- OK dap-go is available

Gotestsum (optional) ~
- OK Binary 'gotestsum' found on PATH: C:\Users\Pablo\go\bin\gotestsum.EXE
```

### Describe the bug

Hello!

I'm getting this odd issue, I am running a dummy test and the plugin says that no test associated, nonetheless the test passed and even 

`	require("neotest").output.open({ enter = true, auto_close = true })`

Returns that the test passed.

![{D7DAF58D-FC1A-424E-9DB6-DBB934053BE2}](https://github.com/user-attachments/assets/38b8459f-add7-4db1-9980-be7621dca717)

something_test.go:

`package main_test

import (
	"math"
	"testing"
)

func TestAbs(t *testing.T) {
    got := math.Abs(-1)
    if got != 1 {
        t.Errorf("Abs(-1) = %f; want 1", got)
    }
}`

:InspectTree returns:

`(source_file ; [0, 0] - [13, 0]
  (package_clause ; [0, 0] - [0, 17]
    (package_identifier)) ; [0, 8] - [0, 17]
  (import_declaration ; [2, 0] - [5, 1]
    (import_spec_list ; [2, 7] - [5, 1]
      (import_spec ; [3, 1] - [3, 7]
        path: (interpreted_string_literal)) ; [3, 1] - [3, 7]
      (import_spec ; [4, 1] - [4, 10]
        path: (interpreted_string_literal)))) ; [4, 1] - [4, 10]
  (function_declaration ; [7, 0] - [12, 1]
    name: (identifier) ; [7, 5] - [7, 12]
    parameters: (parameter_list ; [7, 12] - [7, 26]
      (parameter_declaration ; [7, 13] - [7, 25]
        name: (identifier) ; [7, 13] - [7, 14]
        type: (pointer_type ; [7, 15] - [7, 25]
          (qualified_type ; [7, 16] - [7, 25]
            package: (package_identifier) ; [7, 16] - [7, 23]
            name: (type_identifier))))) ; [7, 24] - [7, 25]
    body: (block ; [7, 27] - [12, 1]
      (short_var_declaration ; [8, 4] - [8, 23]
        left: (expression_list ; [8, 4] - [8, 7]
          (identifier)) ; [8, 4] - [8, 7]
        right: (expression_list ; [8, 11] - [8, 23]
          (call_expression ; [8, 11] - [8, 23]
            function: (selector_expression ; [8, 11] - [8, 19]
              operand: (identifier) ; [8, 11] - [8, 15]
              field: (field_identifier)) ; [8, 16] - [8, 19]
            arguments: (argument_list ; [8, 19] - [8, 23]
              (unary_expression ; [8, 20] - [8, 22]
                operand: (int_literal)))))) ; [8, 21] - [8, 22]
      (if_statement ; [9, 4] - [11, 5]
        condition: (binary_expression ; [9, 7] - [9, 15]
          left: (identifier) ; [9, 7] - [9, 10]
          right: (int_literal)) ; [9, 14] - [9, 15]
        consequence: (block ; [9, 16] - [11, 5]
          (expression_statement ; [10, 8] - [10, 45]
            (call_expression ; [10, 8] - [10, 45]
              function: (selector_expression ; [10, 8] - [10, 16]
                operand: (identifier) ; [10, 8] - [10, 9]
                field: (field_identifier)) ; [10, 10] - [10, 16]
              arguments: (argument_list ; [10, 16] - [10, 45]
                (interpreted_string_literal) ; [10, 17] - [10, 39]
                (identifier))))))))) ; [10, 41] - [10, 44]`

:Inspect returns

![{31772B57-280F-48A1-B1E7-CF9654F02952}](https://github.com/user-attachments/assets/0745882a-edea-4772-9cf3-85fcc364e387)

### Steps To Reproduce

Install nvim
Install plugin as config recommended:

`return {
	{
		"nvim-neotest/neotest",
		dependencies = {
			"nvim-neotest/nvim-nio",
			"nvim-lua/plenary.nvim",
			"antoinemadec/FixCursorHold.nvim",
			"nvim-treesitter/nvim-treesitter",
			"nvim-neotest/neotest-plenary",
			--		"nvim-neotest/neotest-go",
			{
				"fredrikaverpil/neotest-golang",
				version = "*",
				dependencies = {
					{
						"leoluz/nvim-dap-go",
						opts = {},
					},
				},
			}, -- Installation
		},
		opts = function(_, opts)
			opts.adapters = opts.adapters or {}
			opts.adapters["neotest-golang"] = {
				go_test_args = {
					"-v",

					"-coverprofile=" .. vim.fn.getcwd() .. "/coverage.out",
				},
			}
		end,
		config = function(_, opts)
			if opts.adapters then
				local adapters = {}
				for name, config in pairs(opts.adapters or {}) do
					if type(name) == "number" then
						if type(config) == "string" then
							config = require(config)
						end
						adapters[#adapters + 1] = config
					elseif config ~= false then
						local adapter = require(name)
						if type(config) == "table" and not vim.tbl_isempty(config) then
							local meta = getmetatable(adapter)
							if adapter.setup then
								adapter.setup(config)
							elseif adapter.adapter then
								adapter.adapter(config)
								adapter = adapter.adapter
							elseif meta and meta.__call then
								adapter(config)
							else
								error("Adapter " .. name .. " does not support setup")
							end
						end
						adapters[#adapters + 1] = adapter
					end
				end
				opts.adapters = adapters
			end

			require("neotest").setup(opts)
		end,
		keys = {
			{
				"<leader>ta",
				function()
					require("neotest").run.attach()
				end,
				desc = "[t]est [a]ttach",
			},
			{
				"<leader>tf",
				function()
					require("neotest").run.run(vim.fn.expand("%"))
				end,
				desc = "[t]est run [f]ile",
			},
			{
				"<leader>tA",
				function()
					require("neotest").run.run(vim.uv.cwd())
				end,
				desc = "[t]est [A]ll files",
			},
			{
				"<leader>tS",
				function()
					require("neotest").run.run({ suite = true })
				end,
				desc = "[t]est [S]uite",
			},
			{
				"<leader>tn",
				function()
					require("neotest").run.run()
				end,
				desc = "[t]est [n]earest",
			},
			{
				"<leader>tl",
				function()
					require("neotest").run.run_last()
				end,
				desc = "[t]est [l]ast",
			},
			{
				"<leader>ts",
				function()
					require("neotest").summary.toggle()
				end,
				desc = "[t]est [s]ummary",
			},
			{
				"<leader>to",
				function()
					require("neotest").output.open({ enter = true, auto_close = true })
				end,
				desc = "[t]est [o]utput",
			},
			{
				"<leader>tO",
				function()
					require("neotest").output_panel.toggle()
				end,
				desc = "[t]est [O]utput panel",
			},
			{
				"<leader>tt",
				function()
					require("neotest").run.stop()
				end,
				desc = "[t]est [t]erminate",
			},
			{
				"<leader>td",
				function()
					require("neotest").run.run({ suite = false, strategy = "dap" })
				end,
				desc = "Debug nearest test",
			},
			{
				"<leader>tD",
				function()
					require("neotest").run.run({ vim.fn.expand("%"), strategy = "dap" })
				end,
				desc = "Debug current file",
			},
		},
	},
}`

Run nearest test.

### Expected Behavior

The plugin should return a green check in this case

### Your Lua setup

```Lua
return {
	{
		"nvim-neotest/neotest",
		dependencies = {
			"nvim-neotest/nvim-nio",
			"nvim-lua/plenary.nvim",
			"antoinemadec/FixCursorHold.nvim",
			"nvim-treesitter/nvim-treesitter",
			"nvim-neotest/neotest-plenary",
			--		"nvim-neotest/neotest-go",
			{
				"fredrikaverpil/neotest-golang",
				version = "*",
				dependencies = {
					{
						"leoluz/nvim-dap-go",
						opts = {},
					},
				},
			}, -- Installation
		},
		opts = function(_, opts)
			opts.adapters = opts.adapters or {}
			opts.adapters["neotest-golang"] = {
				go_test_args = {
					"-v",

					"-coverprofile=" .. vim.fn.getcwd() .. "/coverage.out",
				},
			}
		end,
		config = function(_, opts)
			if opts.adapters then
				local adapters = {}
				for name, config in pairs(opts.adapters or {}) do
					if type(name) == "number" then
						if type(config) == "string" then
							config = require(config)
						end
						adapters[#adapters + 1] = config
					elseif config ~= false then
						local adapter = require(name)
						if type(config) == "table" and not vim.tbl_isempty(config) then
							local meta = getmetatable(adapter)
							if adapter.setup then
								adapter.setup(config)
							elseif adapter.adapter then
								adapter.adapter(config)
								adapter = adapter.adapter
							elseif meta and meta.__call then
								adapter(config)
							else
								error("Adapter " .. name .. " does not support setup")
							end
						end
						adapters[#adapters + 1] = adapter
					end
				end
				opts.adapters = adapters
			end

			require("neotest").setup(opts)
		end,
		keys = {
			{
				"<leader>ta",
				function()
					require("neotest").run.attach()
				end,
				desc = "[t]est [a]ttach",
			},
			{
				"<leader>tf",
				function()
					require("neotest").run.run(vim.fn.expand("%"))
				end,
				desc = "[t]est run [f]ile",
			},
			{
				"<leader>tA",
				function()
					require("neotest").run.run(vim.uv.cwd())
				end,
				desc = "[t]est [A]ll files",
			},
			{
				"<leader>tS",
				function()
					require("neotest").run.run({ suite = true })
				end,
				desc = "[t]est [S]uite",
			},
			{
				"<leader>tn",
				function()
					require("neotest").run.run()
				end,
				desc = "[t]est [n]earest",
			},
			{
				"<leader>tl",
				function()
					require("neotest").run.run_last()
				end,
				desc = "[t]est [l]ast",
			},
			{
				"<leader>ts",
				function()
					require("neotest").summary.toggle()
				end,
				desc = "[t]est [s]ummary",
			},
			{
				"<leader>to",
				function()
					require("neotest").output.open({ enter = true, auto_close = true })
				end,
				desc = "[t]est [o]utput",
			},
			{
				"<leader>tO",
				function()
					require("neotest").output_panel.toggle()
				end,
				desc = "[t]est [O]utput panel",
			},
			{
				"<leader>tt",
				function()
					require("neotest").run.stop()
				end,
				desc = "[t]est [t]erminate",
			},
			{
				"<leader>td",
				function()
					require("neotest").run.run({ suite = false, strategy = "dap" })
				end,
				desc = "Debug nearest test",
			},
			{
				"<leader>tD",
				function()
					require("neotest").run.run({ vim.fn.expand("%"), strategy = "dap" })
				end,
				desc = "Debug current file",
			},
		},
	},
}
```

**Comment by fredrikaverpil** [comment]
Hi @PabloRai and thanks for the report. I see you are on Windows. Unfortunately, Windows is known for having issues sometimes with truncating the terminal output.

Please try enabling gotestsum (see  the README).

I think it's probably time to add a warning to the health check if you're on Windows...

**Comment by PabloRai** [comment]
Hi @fredrikaverpil 

I used gotestsum and it worked as expected:

![{BB278200-9019-457A-898C-40EAA1711015}](https://github.com/user-attachments/assets/bb4d69b6-1358-4f7a-922a-d59c27ebf898)


Before I could use it I also have to set CGO_ENABLED to 1, and in order to do that I also have to install mingw

**Comment by fredrikaverpil** [comment]
Thanks for trying this out.

I think CGO_ENABLED is required because -race is among the test commands arguments. You can try removing it and see if you can then skip that.

Not sure why you had to install mingw. Could you please elaborate on that?

**Comment by fredrikaverpil** [comment]
I just added a few `:checkhealth neotest-golang` checks, so to hopefully aid Windows users, moving forward.

I'll close this issue for now. Let me know if you think there's something else we can do about this and we can re-open it.
