### ISSUE TITLE
feature: only run test in package instead of go.mod root

### ISSUE THREAD

**Issue by damoye** [fredrikaverpil/neotest-golang#228]
### Did you check docs and existing issues?

- [X] I have read the [documentation](https://github.com/fredrikaverpil/neotest-golang/blob/main/README.md).
- [X] I have searched the existing [issues](https://github.com/fredrikaverpil/neotest-golang/issues).

### Is your feature request related to a problem? Please describe.

When I run
```lua
require("neotest").run.run("<my_package_folder>")
```
It will search up to go.mod and run `go test ./...` from directory of go.mod file.

However I would like to run `go test ./...` only in my_package_folder.

Neotest summary also only shows tests in my_package_folder instead of directory of go.mod file.

### Describe the solution you'd like to see.

Only run all tests in specified package.
Maybe change `run_spec.cwd` from `go_mod_folderpath` to `pos.path` in:
https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/runspec/dir.lua#L63

### Describe alternatives you've considered.

No

**Comment by damoye** [comment]
I find out that my specified package is empty without any go files. So it will run `go test ./...`
If it contains go files. It will only run `go test <my_package_folder>` without `/...`. So it won't run any test in sub folders.
Is this as expected?

**Comment by fredrikaverpil** [comment]
Hi @damoye I'm not sure I understand the issue.

Let's take this repo as an example.
1. Clone down neotest-golang into `~/code/neotest-golang`; `git clone https://github.com/fredrikaverpil/neotest-golang.git ~/code/neotest-golang`
2. `cd neotest-golang`
3. Start Neovim; `nvim`
4. Run `:lua require("neotest").run.run(vim.fn.expand("~/code/neotest-golang/tests/go/subpackage"))`

The command that gets executed is:

```bash
go test -json -v -count=1 -race github.com/fredrikaverpil/neotest-golang/subpackage
```

Can you give an example lua command which exhibits substituting the package with `./...`?

**Comment by damoye** [comment]
@fredrikaverpil Hi, let's use my fork for example: https://github.com/damoye/neotest-golang
File tree like this:
├── subpackage
│   ├── coverage.out
│   └── subpackage2
│       ├── subpackage2_test.go
│       └── subpackage3
│           └── subpackage3_test.go

Note that there is no go file in the subpackage.

### First problem
When I run `:lua require("neotest").run.run(vim.fn.expand("~/code/neotest-golang/tests/go/subpackage"))`
It will run command `go test -json ./...` with cwd  `~/code/neotest-golang/tests/go`.
So it runs all the tests in folder `go`, not `subpackage`.
### Second problem
When I run `:lua require("neotest").run.run(vim.fn.expand("~/code/neotest-golang/tests/go/subpackage/subpackage2"))`
It will run command `go test -json github.com/fredrikaverpil/neotest-golang/subpackage/subpackage2`
But this command only runs test files in `subpackage/subpackage2`, not all packages in subpackage2 recursively, like subpackage3.

**Comment by fredrikaverpil** [comment]
Thank you @damoye I can reproduce. Let me have a closer look at this.

**Comment by fredrikaverpil** [comment]
@damoye wow, I can't believe this bug hasn't been found until now. It was quite severe. Huge thanks for reporting this!

If you have the time, would you please see if this resolves the issues you are seeing on your end?

```lua
{ "fredrikaverpil/neotest-golang", branch = "fix/package" }
```

**Comment by damoye** [comment]
@fredrikaverpil Yes! It resolved my problems. Thansk a lot!
