### ISSUE TITLE
Tests that are not actually run are marked as passing

### ISSUE THREAD

**Issue by jstensland** [fredrikaverpil/neotest-golang#40]
When I trigger an individual test in a testify suite, it is marked as passing even if no test was run.  The run spec produces the following command, which doesn't match the test, due to it being in a testify suite and needing `^SuiteName/TestName$`

```
  command = { "go", "test", "-json", "-v", "-race", "-count=1", "-timeout=60s", "-run", "^TestName$" },
```

 I know that's not supported yet, but if you try to run an individual test and no tests are run, it seems like it should fail and warn, not pass silently

**Comment by fredrikaverpil** [comment]
Good suggestion, and sounds like it could be quite straight forward.

My guess is we could set the status to "skipped" if the "no tests to run" message appears in the output for that test execution.

**Comment by fredrikaverpil** [comment]
@jstensland if you wish, you can give #42 a try by configuring neotest-golang to use the PR's branch:

```diff
return {
  {
    "nvim-neotest/neotest",
+    branch = "skip-tests-not-found",
    dependencies = {
      "nvim-neotest/nvim-nio",
      "nvim-lua/plenary.nvim",
      "antoinemadec/FixCursorHold.nvim",
      "nvim-treesitter/nvim-treesitter",
      "fredrikaverpil/neotest-golang", -- Installation
    },
    config = function()
      require("neotest").setup({
        adapters = {
          require("neotest-golang"), -- Registration
        },
      })
    end,
  },
}
```

**Comment by jstensland** [comment]
Not sure if it's just my setup, but that config looked for `skip-tests-not-found` in the `nvim-neotest/neotest` repo.

I was able to point at your branch though and it works well. Thanks for the quick work!

**Comment by fredrikaverpil** [comment]
Oof, my bad, I edited the post above. I misplaced the `branch` directive! 🤦

**Comment by jstensland** [comment]
Thanks for the edit, as that's simpler than what I did. I'm definitely still learning lua, lazy.nvim etc. I'm still surprised every time you can just trade out the type of a config value between string, table or function. 🤷

**Comment by fredrikaverpil** [comment]
Hehe, yeah, same here. It took some time to wrap my head around that more or less everything in Lua is a table and it's incredibly easy to do mistakes.
